<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Cdsi.Contracts</RootNamespace>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cdsi.Core\Cdsi.Core.csproj" />
  </ItemGroup>

</Project>
